### ISSUE TITLE
 which scripts py copy?

### ISSUE THREAD

**Issue by andrequeiroz2** [jczic/MicroWebSrv2#2]
hello congratulations for the work, I'm in doubt about which py scripts to copy to my esp32, or should I copy everything?

**Comment by jczic** [comment]
You can copy MicroWebSrv2/ and main.py too test it.

**Comment by athusrv** [comment]
@jczic I'm receiving this error when copying `MicroWebSrv2\libs\urlUtils.py` into ESP32:

```
Traceback (most recent call last):
  File "C:\Users\Athus\AppData\Roaming\JetBrains\PyCharm2020.1\plugins\intellij-micropython/scripts/microupload.py", line 139, in <module>
    main(sys.argv[1:])
  File "C:\Users\Athus\AppData\Roaming\JetBrains\PyCharm2020.1\plugins\intellij-micropython/scripts/microupload.py", line 79, in main
    files.put(remote_path, fd.read())
  File "D:\Athus\workspace\asimov\code\esp32\venv\lib\site-packages\ampy\files.py", line 209, in put
    self._pyboard.exec_("f = open('{0}', 'wb')".format(filename))
  File "D:\Athus\workspace\asimov\code\esp32\venv\lib\site-packages\ampy\pyboard.py", line 267, in exec_
    raise PyboardError('exception', ret, ret_err)
ampy.pyboard.PyboardError: ('exception', b'', b'Traceback (most recent call last):\r\n  File "<stdin>", line 1\r\nSyntaxError: invalid syntax\r\n')
```

I'm using Python 3.5
