### ISSUE TITLE
Cannot start webserver, allocate_lock import error

### ISSUE THREAD

**Issue by rfblume** [jczic/MicroWebSrv2#44]
When I try to start the webserver, I always get the following message on a ESP32 using MicroPython (LoBo version)

Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "webServer.py", line 1, in <module>
  File "MicroWebSrv2/__init__.py", line 15, in <module>
  File "MicroWebSrv2/libs/XAsyncSockets.py", line 7, in <module>
ImportError: cannot import name allocate_lock
MicroPython ESP32_LoBo_v3.2.24 - 2018-09-06 on ESP32&psRAM board with ESP32
Type "help()" for more information.

**Comment by RichardAndrews23** [comment]
Same problem, ESP32_LoBo_v3.2.24 '_thread' module does not have 'thread.allocate_lock' method.
