### ISSUE TITLE
MemoryError: memory allocation failed, allocating 136 bytes

### ISSUE THREAD

**Issue by glowingkitty** [jczic/MicroWebSrv2#50]
tried now multiple versions of MicroPython, up to 1.13. But always get the same error on my ESP32 NodeMCU... 
Already split my files as much as possible, but the problem is the MicroWebSrv2 code...
Also tried to compile the MicroWebSrv2 code via `mpy-cross`, but placing them into the same MicroWebSrv2 directory doesn't work - and don't know where to move them instead. I use MacOS 10.15.6  by the way.
`Traceback (most recent call last):
  File "boot.py", line 46, in <module>
  File "stripe.py", line 79, in on
  File "stripe.py", line 30, in start_server
  File "MicroWebSrv2/__init__.py", line 18, in <module>
  File "MicroWebSrv2/microWebSrv2.py", line 13, in <module>
  File "MicroWebSrv2/httpRequest.py", line 8, in <module>
MemoryError: memory allocation failed, allocating 136 bytes`

**Comment by William04A** [comment]
I'm not a repository owner or maintainer, just came here to check in, but I might be able to help. How much memory does your device have? If you are using a PyCom device, some older does not work with the server. You can also try to enable gc to clear up the device RAM, see https://docs.micropython.org/en/latest/library/gc.html.

Good luck!
