### ISSUE TITLE
cannot import name allocate_lock

### ISSUE THREAD

**Issue by erkel1** [jczic/MicroWebSrv2#62]
Hi,

I am getting the below error any ideas?

       ---------------------------
       - Python pkg MicroWebSrv2 -
       -      version 2.0.6      -
       -     by JC`zic & HC2     -
       ---------------------------

Traceback (most recent call last):
  File "main.py", line 3, in <module>
  File "MicroWebSrv2/__init__.py", line 15, in <module>
  File "MicroWebSrv2/libs/XAsyncSockets.py", line 7, in <module>
ImportError: cannot import name allocate_lock
MicroPython ESP32_LoBo_v3.2.24 - 2018-09-06 on ESP32 board with ESP32

**Comment by Quadrangle** [comment]
I long since wrote my own code, but looking at this helped me.I think I wondered about the same thing.  It was due to print statements being in a module that gets imported, and by doing this, print statements were executed.


Sent from Yahoo Mail for iPad


On Monday, February 8, 2021, 9:09 PM, erkel1 <notifications@github.com> wrote:




Hi,

I am getting the below error any ideas?
   ---------------------------
   - Python pkg MicroWebSrv2 -
   -      version 2.0.6      -
   -     by JC`zic & HC2     -
   ---------------------------

Traceback (most recent call last):
File "main.py", line 3, in 
File "MicroWebSrv2/init.py", line 15, in 
File "MicroWebSrv2/libs/XAsyncSockets.py", line 7, in 
ImportError: cannot import name allocate_lock
MicroPython ESP32_LoBo_v3.2.24 - 2018-09-06 on ESP32 board with ESP32
