### ISSUE TITLE
Micropython run error: ImportError: can't import name select

### ISSUE THREAD

**Issue by joyhope** [jczic/MicroWebSrv2#72]
```
../micropython/ports/unix/micropython main.py

       ---------------------------
       - Python pkg MicroWebSrv2 -
       -      version 2.0.6      -
       -     by JC`zic & HC2     -
       ---------------------------

Traceback (most recent call last):
  File "main.py", line 3, in <module>
  File "/...MicroWebSrv2/MicroWebSrv2/__init__.py", line 15, in <module>
  File "/...MicroWebSrv2/MicroWebSrv2/libs/XAsyncSockets.py", line 9, in <module>
ImportError: can't import name select
```

I install the select
```
./micropython/ports/unix/micropython -m upip install micropython-select
Installing to: /home/.../.micropython/lib/
Warning: micropython.org SSL certificate is not validated
Installing micropython-select 0.3 from https://micropython.org/pi/select/select-0.3.tar.gz
Installing micropython-ffilib 0.1.3 from https://micropython.org/pi/ffilib/ffilib-0.1.3.tar.gz
Installing micropython-os 0.6 from https://micropython.org/pi/os/os-0.6.tar.gz
Installing micropython-errno 0.1.4 from https://micropython.org/pi/errno/errno-0.1.4.tar.gz
Installing micropython-stat 0.5.1 from https://micropython.org/pi/stat/stat-0.5.1.tar.gz
```
I install select thought upip, but I still meet the Import error.  

How could I solve the problem?  I try using microWebSrv2 in PC to confirm the development code.

**Comment by joyhope** [comment]
I change XAsyncSocket.py

```
from   select   import select
=>
import select
```

The select import problem is gone, but 

```
MicroWebSrv2Exception: Cannot bind server on 0.0.0.0:8080.  <<==I changed to 8080, it works if using python 
```

**Comment by antonvh** [comment]
I have the same. It is strange, because the MicroPython docs suggest using poll() instead of select():

https://docs.micropython.org/en/latest/library/select.html


I'm running in Micropython 1.17 on MacOS. I was going to develop the server there first before running it on pyboard.
