### ISSUE TITLE
Cannot bind server on 0.0.0.0:80.

### ISSUE THREAD

**Issue by JohannesMaierhofer** [jczic/MicroWebSrv2#76]
Hi, I'm trying to run MicroWebSrv2 on the Arduino RP2040 nano Connect via a wifi connection.
But I ended up in `MicroWebSrv2Exception: Cannot bind server on 0.0.0.0:80.`

Here is my minimal example:

```
import network

SSID ='My_Nano_RP2040_Connect'   # Network SSID
KEY  ='1234567890'  # Network key (must be 10 chars)

# Init wlan module and connect to network
wlan = network.WLAN(network.AP_IF)
wlan.active(True)
wlan.config(essid=SSID, key=KEY, security=wlan.WEP, channel=2)
print("AP mode started. SSID: {} IP: {}".format(SSID, wlan.ifconfig()[0]))

from MicroWebSrv2 import *
from time         import sleep

mws2 = MicroWebSrv2()
mws2.SetEmbeddedConfig()
mws2.StartManaged()

# Main program loop until keyboard interrupt,
try :
    while True :
        sleep(1)
except KeyboardInterrupt :
    mws2.Stop()

```

**Comment by JohannesMaierhofer** [comment]
Additional information: The following line causes the issue, as it seems not available for the RP2 port of usocket.
`srvSocket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)`

**Comment by concentrateddon** [comment]
I'm successfully running MWS2 on a Pico W, but I did have to manually use Bind() to specify my IP address and port, once I connected the W to the WLAN and had an IP. Letting it default-bind to 0.0.0.0 wasn't working.

**Comment by fschlaef** [comment]
> I'm successfully running MWS2 on a Pico W, but I did have to manually use Bind() to specify my IP address and port, once I connected the W to the WLAN and had an IP. Letting it default-bind to 0.0.0.0 wasn't working.

How did you manage to make it work ? Even manually binding the RPI Pico IP address and port, I am still getting the same error `Cannot bind server on 192.168.1.113:8000`, same with port `80 ` and IP `0.0.0.0`

**Comment by washley** [comment]
It's not a good sign that this issue is still open nearly four years later.

I just started trying MicroWebSrv2 on a Pico 2W and am running into the same issue.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "MicroWebSrv2/microWebSrv2.py", line 224, in StartManaged
  File "MicroWebSrv2/microWebSrv2.py", line 216, in StartManaged
  File "MicroWebSrv2/microWebSrv2.py", line 194, in StartInPool
MicroWebSrv2Exception: Cannot bind server on 0.0.0.0:80.
```

[The code](https://github.com/jczic/MicroWebSrv2/blob/master/MicroWebSrv2/libs/XAsyncSockets.py#L420) is doing the equivalent of
```
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
s.bind(('0.0.0.0', 80))
s.listen(8)
```
and is somehow failing, despite that working just fine when I execute it myself. However, if I run it _after_ ```ws.StartManaged()``` fails, then I get EADDRINUSE, suggesting that the bind actually _is_ working, _and_ the socket is getting leaked as well.

Modifying [the exception handler] to rethrow the underlying exception, it's not actually a socket binding issue
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "MicroWebSrv2/microWebSrv2.py", line 225, in StartManaged
  File "MicroWebSrv2/microWebSrv2.py", line 217, in StartManaged
  File "MicroWebSrv2/microWebSrv2.py", line 191, in StartInPool
  File "MicroWebSrv2/libs/XAsyncSockets.py", line 437, in Create
  File "MicroWebSrv2/libs/XAsyncSockets.py", line 224, in NotifyNextReadyForReading
  File "MicroWebSrv2/libs/XAsyncSockets.py", line 93, in _sendUDPSockEvent
OSError: [Errno 113] EHOSTUNREACH
```

The underlying problem there appears to be that micropython's network stack doesn't, at least by default, have a 127.0.0.1 loopback address that [this code](https://github.com/jczic/MicroWebSrv2/blob/master/MicroWebSrv2/libs/XAsyncSockets.py#L40-L46) (reasonably) assumes exists. Here's a demo of the ultimate problem preventing this from working
```
>>> import socket
>>> s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
>>> s.bind(('127.0.0.1', 54321))
>>> s.sendto(b'\xFF', ('127.0.0.1', 54321))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 113] EHOSTUNREACH
```

**Comment by washley** [comment]
I attempted a workaround
```
sp = XAsyncSocketsPool()
# Work around https://github.com/jczic/MicroWebSrv2/issues/76
sp._udpSockEvt.bind((wlan.ifconfig()[0], sp._udpSockEvtAddr[1]))
sp._udpSockEvtAddr = (wlan.ifconfig()[0], sp._udpSockEvtAddr[1])

ws = MicroWebSrv2()
ws.SetEmbeddedConfig()
ws.StartInPool(sp)

sp.AsyncWaitEvents()
```
While that does get the server running, accepting connections, and TCP ACK'ing a sent request, it never writes any response. I came across [this other issue](https://github.com/jczic/MicroWebSrv2/issues/99) that suggests MicroWebSrv2 doesn't work with recent MicroPython versions, so it could just be that issue. Big bummer. Probably going to have to bail on attempting to use this.
